image: alpine/edge
packages:
- bison
- flex
- qbe
- qemu-aarch64
- qemu-openrc
- qemu-riscv64
sources:
- https://git.sr.ht/~mcf/cproc
tasks:
- setup: |
    sudo /etc/init.d/qemu-binfmt start
    for arch in aarch64 riscv64; do
    	mkdir -p $arch/etc/apk
    	cp /etc/apk/repositories $arch/etc/apk
    	apk add -p $arch --arch $arch --allow-untrusted --initdb --usermode alpine-baselayout busybox gcc musl-dev make qbe
    	sudo mount -t proc none $arch/proc
    	sudo mount -t tmpfs none $arch/tmp
    	sudo mount --rbind /dev $arch/dev
    	mkdir $arch/cproc
    	git -C cproc --work-tree $PWD/$arch/cproc checkout HEAD .
    done
    patch -p0 -d riscv64/usr/include < cproc/.builds/musl-riscv64.diff
- build: |
    cd cproc
    ./configure
    make all check bootstrap check-stage2
- build-c99: |
    cd cproc
    git clean -dfx
    ./configure 'CFLAGS=-std=c99 -Werror=pedantic'
    make
- build-aarch64: |
    sudo chroot aarch64 sh -ec '
    	cd cproc
    	./configure
    	make all check bootstrap
    	readelf -h stage2/cproc stage2/cproc-qbe
    '
- build-riscv64: |
    sudo chroot riscv64 sh -ec '
    	cd cproc
    	./configure
    	make all check bootstrap
    	readelf -h stage2/cproc stage2/cproc-qbe
    '
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
