image: alpine/latest
packages:
- qemu-riscv64
- qemu-openrc
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
tasks:
- setup: |
    sudo /etc/init.d/qemu-binfmt start
    curl -O http://musl.cc/riscv64-linux-musl-cross.tgz
    tar --warning=no-unknown-keyword -xzf riscv64-linux-musl-cross.tgz
    patch -p0 -d riscv64-linux-musl-cross/riscv64-linux-musl/include < cproc/.builds/musl-riscv64.diff
- build: |
    PATH=$HOME/qbe:$HOME/riscv64-linux-musl-cross/bin:$PATH
    make -C qbe
    cd cproc
    ./configure \
      --target=riscv64-linux-musl \
      --with-ldso="$HOME/riscv64-linux-musl-cross/riscv64-linux-musl/lib/libc.so" \
      CFLAGS='-std=c11'
    make all check bootstrap
    file stage2/cproc stage2/cproc-qbe
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
