image: alpine/latest
packages:
- qemu-aarch64
- qemu-openrc
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
tasks:
- setup: |
    sudo /etc/init.d/qemu-binfmt start
    curl -O http://musl.cc/aarch64-linux-musl-cross.tgz
    tar --warning=no-unknown-keyword -xzf aarch64-linux-musl-cross.tgz
- build: |
    PATH=$HOME/qbe:$HOME/aarch64-linux-musl-cross/bin:$PATH
    make -C qbe
    cd cproc
    ./configure \
      --target=aarch64-linux-musl \
      --with-ldso="$HOME/aarch64-linux-musl-cross/aarch64-linux-musl/lib/libc.so"
    make all check bootstrap
    file stage2/cproc stage2/cproc-qbe
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
