image: debian/stable
packages:
- gcc-aarch64-linux-gnu
- libc-dev-arm64-cross
- qemu-user
- qemu-user-binfmt
sources:
- https://git.sr.ht/~mcf/cproc
- https://git.sr.ht/~mcf/qbe
tasks:
- build: |
    PATH=$HOME/qbe:$PATH
    cd qbe
    cat >config.h <<EOF
    #define Defasm Gaself
    #define Deftgt T_arm64
    EOF
    make
    cd ../cproc
    crtbegin=$(aarch64-linux-gnu-gcc -print-file-name=crtbegin.o)
    ./configure \
      --target=aarch64-linux-gnu \
      --with-ldso=/usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
      --with-gcc-libdir="${crtbegin%/*}"
    make all check
    make bootstrap LDFLAGS='-Wl,-rpath,/usr/aarch64-linux-gnu/lib'
    aarch64-linux-gnu-readelf -h stage2/cproc stage2/cproc-qbe
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
