image: debian/stretch
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
tasks:
- build: |
    PATH=$HOME/qbe/obj:$PATH
    make -C qbe
    cd cproc
    ./configure
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: ~mcf/cproc@lists.sr.ht
