image: debian/stable
packages:
- qbe
sources:
- https://git.sr.ht/~mcf/cproc
tasks:
- build: |
    cd cproc
    ./configure
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
