image: netbsd/latest
packages:
- qbe
sources:
- https://git.sr.ht/~mcf/cproc
tasks:
- setup: |
    sudo patch -p1 -d /usr/include < cproc/.builds/netbsd.diff
- build: |
    cd cproc
    ./configure
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
