image: nixos/latest
sources:
- https://git.sr.ht/~mcf/cproc
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
packages:
- nixpkgs.gcc
- nixpkgs.gnumake
- nixpkgs.qbe
tasks:
- build: |
    cd cproc
    ./configure --with-ldso=
    make all check bootstrap check-stage2
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
