image: openbsd/latest
packages:
- gas
- qbe
sources:
- https://git.sr.ht/~mcf/cproc
tasks:
- setup: |
    # use __builtin_va_* even on non __GNUC__ compilers
    doas patch -d /usr/include < cproc/.builds/openbsd.diff
- build: |
    cd cproc
    ./configure --with-as=gas
    make all check bootstrap check-stage2
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
