name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-15-intel, macos-26-intel]
        include:
        - os: macos-latest
          config: --host=aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: qbe
      run: |
        git clone -b arm64-extern-offset https://git.sr.ht/~mcf/qbe
        make -C qbe install
    - name: setup
      run: sudo patch -d "$(xcrun --show-sdk-path)" -i "$PWD/.github/workflows/macos.diff"
    - name: build
      run: ./configure ${{ matrix.config }} && make
    - name: test
      run: make check
    - name: bootstrap
      run: make -k bootstrap
    - name: test stage3
      run: make check-stage2
